module.exports = {
  main: `{{> header }}

{{! Blocks with say statement }}
{{#say}}
{{> say}}
{{/say}}

{{! Blocks with strings }}
{{#string.length}}
translate {{language}} strings:
  {{#string}}
    {{> string}}
  {{/string}}
{{/string.length}}`,

  partials: {
    header: '# Generated by renpy-translate-utils\n# Created at {{ date }}',
    say: `
{{#meta.source}}
# {{{file}}}:{{line}}
{{/meta.source}}
translate {{language}} {{meta.id}}:

  {{#original}}
    #{{#who}} {{{.}}}{{/who}} "{{{what}}}"{{#meta.nointeract}} nointeract{{/meta.nointeract}}{{#with}} {{.}}{{/with}}
  {{/original}}
  {{#translated}}
    {{#who}}{{{.}}}{{/who}} "{{{what}}}"{{#meta.nointeract}} nointeract{{/meta.nointeract}}{{#with}} {{.}}{{/with}}
  {{/translated}}
  {{^translated}}
    pass
  {{/translated}}`,
    string: `
{{#meta.source}}
# {{{file}}}:{{line}}
{{/meta.source}}
{{#original}}
old "{{{what}}}"
{{/original}}
{{#translated}}
new "{{{what}}}"
{{/translated}}`
  }
};
